kind = "web"
previewPath = "/"
title = "Поиск по книгам"
version = "1.0.0"
id = "artifacts/book-search"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
localPort = 25954
name = "web"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/book-search run dev"

[services.env]
PORT = "25954"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/book-search", "run", "build"]
publicDir = "artifacts/book-search/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"
