[[pages]]
path = "/"
screenshotTimestamp = "2026-03-24T15:47:45Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/e6d84a05-037d-49b8-b7c7-142d6e3a28bf/00c42bac-732a-4ade-9ebf-ebed14f439a9/WDOJAVY"
